-- Этот файл был сгенерирован тНавигатор v23.4-5689-g1082f6c1238f.
-- Copyright (C) Рок Флоу Динамикс 2005-2024.
-- Все права защищены.


EQUIL
-- depth  pres depth-wo pres-wo depth-go pres-go rsvd rvvd accuracy
   2387.5 259  2412     0       2387.5   0       0    /


RSVD
-- depth rs
   -100  100
    100  200
/

--Name of the property in Model Designer: SGAS 
INCLUDE
'INCLUDE/DynamicModel_SGAS.inc' /

--Name of the property in Model Designer: SOIL 
INCLUDE
'INCLUDE/DynamicModel_SOIL.inc' /

--Name of the property in Model Designer: SWAT 
INCLUDE
'INCLUDE/DynamicModel_SWAT.inc' /

