-- Этот файл был сгенерирован тНавигатор v23.3-4280-ged8ebf643115.
-- Copyright (C) Рок Флоу Динамикс 2005-2023.
-- Все права защищены.

INCLUDE
'INCLUDE/DynamicModel_PVT.inc' /


DENSITY
-- oil water gas  (sc)
   799 1050  0.98 /


ROCK
-- pressure rock-compres (rock-matrix-compres block-compres porosity Poisson-coef)
   259      0.00005      /


STCOND
 15.56 1.01325 /
INCLUDE
'INCLUDE/DynamicModel_RP.inc' /

