-- Этот файл был сгенерирован тНавигатор v23.3-4280-ged8ebf643115.
-- Copyright (C) Рок Флоу Динамикс 2005-2023.
-- Все права защищены.


COREYWO
-- SWL SWU SWCR SOWCR KROLW KRORW KRWR KRWU PCOW NOW NW NP SPC0
   0   1   0    0     1     1     1    1    0    4   4  4  -1   /


COREYGO
-- SGL SGU SGCR SOGCR KROLG KRORG KRGR KRGU PCOG NOG NG NPG SPCG
   0   1   0    0     1     1     1    1    0    4   4  4   -1   /

