-- Этот файл был сгенерирован тНавигатор v24.2-3498-g34c7c60ee388.
-- Copyright (C) Рок Флоу Динамикс 2005-2024.
-- Все права защищены.


RSVD
-- depth rs
   -100  100
    100  200
/

--Name of the property in Model Designer: PBUB 
INCLUDE
'INCLUDE/DYNAMICMODEL_PBUB.inc' /

--Name of the property in Model Designer: PRESSURE 
INCLUDE
'INCLUDE/DYNAMICMODEL_PRESSURE.inc' /

--Name of the property in Model Designer: SGAS 
INCLUDE
'INCLUDE/DYNAMICMODEL_SGAS.inc' /

--Name of the property in Model Designer: SOIL 
INCLUDE
'INCLUDE/DYNAMICMODEL_SOIL.inc' /

--Name of the property in Model Designer: SWAT 
INCLUDE
'INCLUDE/DYNAMICMODEL_SWAT.inc' /

