-- Этот файл был сгенерирован тНавигатор v23.4-5689-g1082f6c1238f.
-- Copyright (C) Рок Флоу Динамикс 2005-2024.
-- Все права защищены.

-- The data used in the model: 
-- Project: RP Project
-- Version: Variant 1

COREYWO
-- SWL   SWU SWCR SOWCR KROLW KRORW KRWR KRWU PCOW NOW NW  NP SPC0
   0.014 1   0.2  0.2   0.9   0.5   0.6  1    0    8   2.5 4  -1   /


COREYGO
-- SGL SGU  SGCR SOGCR KROLG KRORG KRGR KRGU PCOG NOG NG NPG SPCG
   0   0.75 0    0.25  0.9   0.6   0.75 1    0    2   9  4   -1   /

