-- Этот файл был сгенерирован тНавигатор v23.3-4280-ged8ebf643115.
-- Copyright (C) Рок Флоу Динамикс 2005-2023.
-- Все права защищены.


EQUIL
-- depth  pres depth-wo pres-wo depth-go pres-go rsvd rvvd accuracy
   2387.5 259  2412     0       2387.5   0       0    /


RSVD
-- depth rs
   -100  100
    100  200
/

INCLUDE
'INCLUDE/DynamicModel_SGAS.inc' /

INCLUDE
'INCLUDE/DynamicModel_SOIL.inc' /

INCLUDE
'INCLUDE/DynamicModel_SWAT.inc' /

