-- Этот файл был сгенерирован тНавигатор v23.3-4280-ged8ebf643115.
-- Copyright (C) Рок Флоу Динамикс 2005-2023.
-- Все права защищены.


COREYWO
-- SWL   SWU SWCR SOWCR KROLW KRORW KRWR KRWU PCOW NOW NW  NP SPC0
   0.014 1   0.2  0.2   0.9   0.5   0.6  1    0    8   2.5 4  -1   /


COREYGO
-- SGL SGU  SGCR SOGCR KROLG KRORG KRGR KRGU PCOG NOG NG NPG SPCG
   0   0.75 0    0.25  0.9   0.6   0.75 1    0    2   9  4   -1   /

